CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
CONFIG += no_fixpath
QT = core opengl gui widgets
